/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'
import { Route as DevicesDeviceIdProcessesRouteImport } from './routes/devices/$deviceId/processes'
import { Route as DevicesDeviceIdNetworkRouteImport } from './routes/devices/$deviceId/network'
import { Route as DevicesDeviceIdMemoryRouteImport } from './routes/devices/$deviceId/memory'
import { Route as DevicesDeviceIdLogsRouteImport } from './routes/devices/$deviceId/logs'
import { Route as DevicesDeviceIdHooksRouteImport } from './routes/devices/$deviceId/hooks'
import { Route as DevicesDeviceIdFilesRouteImport } from './routes/devices/$deviceId/files'
import { Route as DevicesDeviceIdCryptoRouteImport } from './routes/devices/$deviceId/crypto'
import { Route as DevicesDeviceIdCrashesRouteImport } from './routes/devices/$deviceId/crashes'
import { Route as DevicesDeviceIdClassesRouteImport } from './routes/devices/$deviceId/classes'
import { Route as DevicesDeviceIdAppsRouteImport } from './routes/devices/$deviceId/apps'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdProcessesRoute =
  DevicesDeviceIdProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => DevicesDeviceIdRoute,
  } as any)
const DevicesDeviceIdNetworkRoute = DevicesDeviceIdNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdMemoryRoute = DevicesDeviceIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdLogsRoute = DevicesDeviceIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdHooksRoute = DevicesDeviceIdHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdFilesRoute = DevicesDeviceIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdCryptoRoute = DevicesDeviceIdCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdCrashesRoute = DevicesDeviceIdCrashesRouteImport.update({
  id: '/crashes',
  path: '/crashes',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdClassesRoute = DevicesDeviceIdClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdAppsRoute = DevicesDeviceIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/classes': typeof DevicesDeviceIdClassesRoute
  '/devices/$deviceId/crashes': typeof DevicesDeviceIdCrashesRoute
  '/devices/$deviceId/crypto': typeof DevicesDeviceIdCryptoRoute
  '/devices/$deviceId/files': typeof DevicesDeviceIdFilesRoute
  '/devices/$deviceId/hooks': typeof DevicesDeviceIdHooksRoute
  '/devices/$deviceId/logs': typeof DevicesDeviceIdLogsRoute
  '/devices/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
  '/devices/$deviceId/network': typeof DevicesDeviceIdNetworkRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/classes': typeof DevicesDeviceIdClassesRoute
  '/devices/$deviceId/crashes': typeof DevicesDeviceIdCrashesRoute
  '/devices/$deviceId/crypto': typeof DevicesDeviceIdCryptoRoute
  '/devices/$deviceId/files': typeof DevicesDeviceIdFilesRoute
  '/devices/$deviceId/hooks': typeof DevicesDeviceIdHooksRoute
  '/devices/$deviceId/logs': typeof DevicesDeviceIdLogsRoute
  '/devices/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
  '/devices/$deviceId/network': typeof DevicesDeviceIdNetworkRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/classes': typeof DevicesDeviceIdClassesRoute
  '/devices/$deviceId/crashes': typeof DevicesDeviceIdCrashesRoute
  '/devices/$deviceId/crypto': typeof DevicesDeviceIdCryptoRoute
  '/devices/$deviceId/files': typeof DevicesDeviceIdFilesRoute
  '/devices/$deviceId/hooks': typeof DevicesDeviceIdHooksRoute
  '/devices/$deviceId/logs': typeof DevicesDeviceIdLogsRoute
  '/devices/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
  '/devices/$deviceId/network': typeof DevicesDeviceIdNetworkRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/classes'
    | '/devices/$deviceId/crashes'
    | '/devices/$deviceId/crypto'
    | '/devices/$deviceId/files'
    | '/devices/$deviceId/hooks'
    | '/devices/$deviceId/logs'
    | '/devices/$deviceId/memory'
    | '/devices/$deviceId/network'
    | '/devices/$deviceId/processes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/classes'
    | '/devices/$deviceId/crashes'
    | '/devices/$deviceId/crypto'
    | '/devices/$deviceId/files'
    | '/devices/$deviceId/hooks'
    | '/devices/$deviceId/logs'
    | '/devices/$deviceId/memory'
    | '/devices/$deviceId/network'
    | '/devices/$deviceId/processes'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/classes'
    | '/devices/$deviceId/crashes'
    | '/devices/$deviceId/crypto'
    | '/devices/$deviceId/files'
    | '/devices/$deviceId/hooks'
    | '/devices/$deviceId/logs'
    | '/devices/$deviceId/memory'
    | '/devices/$deviceId/network'
    | '/devices/$deviceId/processes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId/processes': {
      id: '/devices/$deviceId/processes'
      path: '/processes'
      fullPath: '/devices/$deviceId/processes'
      preLoaderRoute: typeof DevicesDeviceIdProcessesRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/network': {
      id: '/devices/$deviceId/network'
      path: '/network'
      fullPath: '/devices/$deviceId/network'
      preLoaderRoute: typeof DevicesDeviceIdNetworkRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/memory': {
      id: '/devices/$deviceId/memory'
      path: '/memory'
      fullPath: '/devices/$deviceId/memory'
      preLoaderRoute: typeof DevicesDeviceIdMemoryRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/logs': {
      id: '/devices/$deviceId/logs'
      path: '/logs'
      fullPath: '/devices/$deviceId/logs'
      preLoaderRoute: typeof DevicesDeviceIdLogsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/hooks': {
      id: '/devices/$deviceId/hooks'
      path: '/hooks'
      fullPath: '/devices/$deviceId/hooks'
      preLoaderRoute: typeof DevicesDeviceIdHooksRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/files': {
      id: '/devices/$deviceId/files'
      path: '/files'
      fullPath: '/devices/$deviceId/files'
      preLoaderRoute: typeof DevicesDeviceIdFilesRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/crypto': {
      id: '/devices/$deviceId/crypto'
      path: '/crypto'
      fullPath: '/devices/$deviceId/crypto'
      preLoaderRoute: typeof DevicesDeviceIdCryptoRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/crashes': {
      id: '/devices/$deviceId/crashes'
      path: '/crashes'
      fullPath: '/devices/$deviceId/crashes'
      preLoaderRoute: typeof DevicesDeviceIdCrashesRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/classes': {
      id: '/devices/$deviceId/classes'
      path: '/classes'
      fullPath: '/devices/$deviceId/classes'
      preLoaderRoute: typeof DevicesDeviceIdClassesRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/apps': {
      id: '/devices/$deviceId/apps'
      path: '/apps'
      fullPath: '/devices/$deviceId/apps'
      preLoaderRoute: typeof DevicesDeviceIdAppsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
  }
}

interface DevicesDeviceIdRouteChildren {
  DevicesDeviceIdAppsRoute: typeof DevicesDeviceIdAppsRoute
  DevicesDeviceIdClassesRoute: typeof DevicesDeviceIdClassesRoute
  DevicesDeviceIdCrashesRoute: typeof DevicesDeviceIdCrashesRoute
  DevicesDeviceIdCryptoRoute: typeof DevicesDeviceIdCryptoRoute
  DevicesDeviceIdFilesRoute: typeof DevicesDeviceIdFilesRoute
  DevicesDeviceIdHooksRoute: typeof DevicesDeviceIdHooksRoute
  DevicesDeviceIdLogsRoute: typeof DevicesDeviceIdLogsRoute
  DevicesDeviceIdMemoryRoute: typeof DevicesDeviceIdMemoryRoute
  DevicesDeviceIdNetworkRoute: typeof DevicesDeviceIdNetworkRoute
  DevicesDeviceIdProcessesRoute: typeof DevicesDeviceIdProcessesRoute
}

const DevicesDeviceIdRouteChildren: DevicesDeviceIdRouteChildren = {
  DevicesDeviceIdAppsRoute: DevicesDeviceIdAppsRoute,
  DevicesDeviceIdClassesRoute: DevicesDeviceIdClassesRoute,
  DevicesDeviceIdCrashesRoute: DevicesDeviceIdCrashesRoute,
  DevicesDeviceIdCryptoRoute: DevicesDeviceIdCryptoRoute,
  DevicesDeviceIdFilesRoute: DevicesDeviceIdFilesRoute,
  DevicesDeviceIdHooksRoute: DevicesDeviceIdHooksRoute,
  DevicesDeviceIdLogsRoute: DevicesDeviceIdLogsRoute,
  DevicesDeviceIdMemoryRoute: DevicesDeviceIdMemoryRoute,
  DevicesDeviceIdNetworkRoute: DevicesDeviceIdNetworkRoute,
  DevicesDeviceIdProcessesRoute: DevicesDeviceIdProcessesRoute,
}

const DevicesDeviceIdRouteWithChildren = DevicesDeviceIdRoute._addFileChildren(
  DevicesDeviceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
