/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'
import { Route as DevicesDeviceIdIndexRouteImport } from './routes/devices/$deviceId/index'
import { Route as DevicesDeviceIdProcessesRouteImport } from './routes/devices/$deviceId/processes'
import { Route as DevicesDeviceIdAppsRouteImport } from './routes/devices/$deviceId/apps'
import { Route as DevicesDeviceIdSessionBundleIdRouteImport } from './routes/devices/$deviceId/session/$bundleId'
import { Route as DevicesDeviceIdSessionBundleIdIndexRouteImport } from './routes/devices/$deviceId/session/$bundleId/index'
import { Route as DevicesDeviceIdSessionBundleIdNetworkRouteImport } from './routes/devices/$deviceId/session/$bundleId/network'
import { Route as DevicesDeviceIdSessionBundleIdLogsRouteImport } from './routes/devices/$deviceId/session/$bundleId/logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdIndexRoute = DevicesDeviceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdProcessesRoute =
  DevicesDeviceIdProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => DevicesDeviceIdRoute,
  } as any)
const DevicesDeviceIdAppsRoute = DevicesDeviceIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdSessionBundleIdRoute =
  DevicesDeviceIdSessionBundleIdRouteImport.update({
    id: '/session/$bundleId',
    path: '/session/$bundleId',
    getParentRoute: () => DevicesDeviceIdRoute,
  } as any)
const DevicesDeviceIdSessionBundleIdIndexRoute =
  DevicesDeviceIdSessionBundleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DevicesDeviceIdSessionBundleIdRoute,
  } as any)
const DevicesDeviceIdSessionBundleIdNetworkRoute =
  DevicesDeviceIdSessionBundleIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => DevicesDeviceIdSessionBundleIdRoute,
  } as any)
const DevicesDeviceIdSessionBundleIdLogsRoute =
  DevicesDeviceIdSessionBundleIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DevicesDeviceIdSessionBundleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
  '/devices/$deviceId/': typeof DevicesDeviceIdIndexRoute
  '/devices/$deviceId/session/$bundleId': typeof DevicesDeviceIdSessionBundleIdRouteWithChildren
  '/devices/$deviceId/session/$bundleId/logs': typeof DevicesDeviceIdSessionBundleIdLogsRoute
  '/devices/$deviceId/session/$bundleId/network': typeof DevicesDeviceIdSessionBundleIdNetworkRoute
  '/devices/$deviceId/session/$bundleId/': typeof DevicesDeviceIdSessionBundleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
  '/devices/$deviceId': typeof DevicesDeviceIdIndexRoute
  '/devices/$deviceId/session/$bundleId/logs': typeof DevicesDeviceIdSessionBundleIdLogsRoute
  '/devices/$deviceId/session/$bundleId/network': typeof DevicesDeviceIdSessionBundleIdNetworkRoute
  '/devices/$deviceId/session/$bundleId': typeof DevicesDeviceIdSessionBundleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/apps': typeof DevicesDeviceIdAppsRoute
  '/devices/$deviceId/processes': typeof DevicesDeviceIdProcessesRoute
  '/devices/$deviceId/': typeof DevicesDeviceIdIndexRoute
  '/devices/$deviceId/session/$bundleId': typeof DevicesDeviceIdSessionBundleIdRouteWithChildren
  '/devices/$deviceId/session/$bundleId/logs': typeof DevicesDeviceIdSessionBundleIdLogsRoute
  '/devices/$deviceId/session/$bundleId/network': typeof DevicesDeviceIdSessionBundleIdNetworkRoute
  '/devices/$deviceId/session/$bundleId/': typeof DevicesDeviceIdSessionBundleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices/$deviceId'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/processes'
    | '/devices/$deviceId/'
    | '/devices/$deviceId/session/$bundleId'
    | '/devices/$deviceId/session/$bundleId/logs'
    | '/devices/$deviceId/session/$bundleId/network'
    | '/devices/$deviceId/session/$bundleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/processes'
    | '/devices/$deviceId'
    | '/devices/$deviceId/session/$bundleId/logs'
    | '/devices/$deviceId/session/$bundleId/network'
    | '/devices/$deviceId/session/$bundleId'
  id:
    | '__root__'
    | '/'
    | '/devices/$deviceId'
    | '/devices/$deviceId/apps'
    | '/devices/$deviceId/processes'
    | '/devices/$deviceId/'
    | '/devices/$deviceId/session/$bundleId'
    | '/devices/$deviceId/session/$bundleId/logs'
    | '/devices/$deviceId/session/$bundleId/network'
    | '/devices/$deviceId/session/$bundleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId/': {
      id: '/devices/$deviceId/'
      path: '/'
      fullPath: '/devices/$deviceId/'
      preLoaderRoute: typeof DevicesDeviceIdIndexRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/processes': {
      id: '/devices/$deviceId/processes'
      path: '/processes'
      fullPath: '/devices/$deviceId/processes'
      preLoaderRoute: typeof DevicesDeviceIdProcessesRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/apps': {
      id: '/devices/$deviceId/apps'
      path: '/apps'
      fullPath: '/devices/$deviceId/apps'
      preLoaderRoute: typeof DevicesDeviceIdAppsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/session/$bundleId': {
      id: '/devices/$deviceId/session/$bundleId'
      path: '/session/$bundleId'
      fullPath: '/devices/$deviceId/session/$bundleId'
      preLoaderRoute: typeof DevicesDeviceIdSessionBundleIdRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/session/$bundleId/': {
      id: '/devices/$deviceId/session/$bundleId/'
      path: '/'
      fullPath: '/devices/$deviceId/session/$bundleId/'
      preLoaderRoute: typeof DevicesDeviceIdSessionBundleIdIndexRouteImport
      parentRoute: typeof DevicesDeviceIdSessionBundleIdRoute
    }
    '/devices/$deviceId/session/$bundleId/network': {
      id: '/devices/$deviceId/session/$bundleId/network'
      path: '/network'
      fullPath: '/devices/$deviceId/session/$bundleId/network'
      preLoaderRoute: typeof DevicesDeviceIdSessionBundleIdNetworkRouteImport
      parentRoute: typeof DevicesDeviceIdSessionBundleIdRoute
    }
    '/devices/$deviceId/session/$bundleId/logs': {
      id: '/devices/$deviceId/session/$bundleId/logs'
      path: '/logs'
      fullPath: '/devices/$deviceId/session/$bundleId/logs'
      preLoaderRoute: typeof DevicesDeviceIdSessionBundleIdLogsRouteImport
      parentRoute: typeof DevicesDeviceIdSessionBundleIdRoute
    }
  }
}

interface DevicesDeviceIdSessionBundleIdRouteChildren {
  DevicesDeviceIdSessionBundleIdLogsRoute: typeof DevicesDeviceIdSessionBundleIdLogsRoute
  DevicesDeviceIdSessionBundleIdNetworkRoute: typeof DevicesDeviceIdSessionBundleIdNetworkRoute
  DevicesDeviceIdSessionBundleIdIndexRoute: typeof DevicesDeviceIdSessionBundleIdIndexRoute
}

const DevicesDeviceIdSessionBundleIdRouteChildren: DevicesDeviceIdSessionBundleIdRouteChildren =
  {
    DevicesDeviceIdSessionBundleIdLogsRoute:
      DevicesDeviceIdSessionBundleIdLogsRoute,
    DevicesDeviceIdSessionBundleIdNetworkRoute:
      DevicesDeviceIdSessionBundleIdNetworkRoute,
    DevicesDeviceIdSessionBundleIdIndexRoute:
      DevicesDeviceIdSessionBundleIdIndexRoute,
  }

const DevicesDeviceIdSessionBundleIdRouteWithChildren =
  DevicesDeviceIdSessionBundleIdRoute._addFileChildren(
    DevicesDeviceIdSessionBundleIdRouteChildren,
  )

interface DevicesDeviceIdRouteChildren {
  DevicesDeviceIdAppsRoute: typeof DevicesDeviceIdAppsRoute
  DevicesDeviceIdProcessesRoute: typeof DevicesDeviceIdProcessesRoute
  DevicesDeviceIdIndexRoute: typeof DevicesDeviceIdIndexRoute
  DevicesDeviceIdSessionBundleIdRoute: typeof DevicesDeviceIdSessionBundleIdRouteWithChildren
}

const DevicesDeviceIdRouteChildren: DevicesDeviceIdRouteChildren = {
  DevicesDeviceIdAppsRoute: DevicesDeviceIdAppsRoute,
  DevicesDeviceIdProcessesRoute: DevicesDeviceIdProcessesRoute,
  DevicesDeviceIdIndexRoute: DevicesDeviceIdIndexRoute,
  DevicesDeviceIdSessionBundleIdRoute:
    DevicesDeviceIdSessionBundleIdRouteWithChildren,
}

const DevicesDeviceIdRouteWithChildren = DevicesDeviceIdRoute._addFileChildren(
  DevicesDeviceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
